### ISSUE TITLE
App not working at all

### ISSUE THREAD

**Issue by shyambandla** [dmalukov/TComTest#1]
please update app

**Comment by dmalukov** [comment]
I will. Until that you can use Android 8 emulator as a workaround.

**Comment by dmalukov** [comment]
@shyambandla I've updated the repo. Android 12 support has been added.

**Comment by shyambandla** [comment]
Thank you

**Comment by dmalukov** [comment]
Closing the issue. Feel free to reopen it if something goes wrong.

**Comment by shyambandla** [comment]
Thank you!
